config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { edit: 'account' }, controllers: { registrations: 'registrations',
                                                                               sessions: 'sessions' }

  resources :categories do
    resources :operations, except: %i[index show]
  end

  resources :operations, only: %i[index show update]

  get 'categories/:id/operations', to: redirect('categories/%{id}')

  get 'my_budget', to: 'budget#index'
  get 'my_budget/deposit', to: 'budget#new_deposit'
  post 'my_budget/deposit', to: 'budget#exec_deposit'
  get 'my_budget/withdraw', to: 'budget#new_withdraw'
  post 'my_budget/withdraw', to: 'budget#exec_withdraw'

  # devise_scope :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   get 'sign_up', to: 'devise/registrations#new'
  #   get 'account', to: 'devise/registrations#edit'
  #   get 'password/new', to: 'devise/passwords#new'
  #   get 'password/edit', to: 'devise/passwords#edit'
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "categories#index"

  get 'get-image', to: 'utils#fetch_image'
end

app/controllers/budget_controller.rb
class BudgetController < ApplicationController
  before_action :authenticate_user!
  before_action :check_params, only: [:index]

  def index
    @user_ops_without_balance_ops = current_user.operations.where
      .not(id: current_user.categories.joins(:categories_operations).where(name: 'personal_budget')
                .pluck(:operation_id))
    @total_expenses = @user_ops_without_balance_ops.sum(:amount).abs
    @total_deposits = current_user.operations.where(name: 'Deposit').sum(:amount)
    @total_withdrawals = current_user.operations.where(name: 'Withdraw').sum(:amount)
    @categories_expenses = order_chart_data bar_chart_data
    @last_days_ops = last_days_expenses params[:lchart_days].to_i
    budget_operations = current_user.categories.find_by(name: 'personal_budget').operations
    @budget_operations_length = budget_operations.length
    @user_budget_ops = budget_operations.order(created_at: :desc)
      .limit(params[:page_items].to_i).offset(params[:page].to_i * params[:page_items].to_i)
  end

  def new_deposit
    render_new_transaction
  end

  def exec_deposit
    @operation = balance_operation 'Deposit'
    operation_amount = operation_params[:amount]

    @operation.transaction do
      @operation.save!
      current_user.update! balance: current_user.balance + operation_params[:amount].to_f
      raise ActiveRecord::RecordInvalid if amount_negative? operation_amount
    end
    redirect_to my_budget_path, notice: 'Deposit processed successfully!'
  rescue ActiveRecord::RecordInvalid
    current_user.balance = current_user.balance_was
    @operation.invalidate_negative_amount if amount_negative? operation_amount
    render :new_transaction, status: :unprocessable_entity
  end

  def new_withdraw
    render_new_transaction
  end

  def exec_withdraw
    @operation = balance_operation 'Withdraw'
    operation_amount = operation_params[:amount].to_f

    @operation.transaction do
      @operation.save!
      if (operation_amount > current_user.balance) || amount_negative?(operation_amount)
        raise ActiveRecord::RecordInvalid
      end

      current_user.update! balance: current_user.balance - operation_amount
    end
    redirect_to my_budget_path, notice: 'Withdrawal processed successfully!'
  rescue ActiveRecord::RecordInvalid
    current_user.balance = current_user.balance_was
    @operation.invalidate_user_balance if operation_amount > current_user.balance
    @operation.invalidate_negative_amount if amount_negative? operation_amount
    render :new_transaction, status: :unprocessable_entity and return
  end

  private

  def balance_operation(name)
    o = Operation.new(**operation_params, name:, categories: [current_user.categories.first], user: current_user)
    o.amount = o.amount.to_f
    o.amount = -o.amount if name == 'Withdraw'
    o
  end

  def render_new_transaction
    @operation = Operation.new
    render 'new_transaction'
  end

  def operation_params
    params.require(:operation).permit(:amount, :description)
  end

  def order_chart_data(list)
    list = list.sort { |a, b| b[:total] <=> a[:total] }
    if list.length > 4
      list[3] = {
        name: 'Others',
        total: list[3..].reduce(0) { |total, item| total + item[:total] }.truncate(2)
      }
    end
    list.first 4
  end

  def last_days_expenses(days_amount = 7)
    days_amount -= 1
    days_ops = @user_ops_without_balance_ops.where(created_at: (Time.now.utc.midnight - days_amount.days)..Time.now.utc)
      .select('SUM(amount) AS total, CAST(created_at AS date)').group('CAST(created_at AS date)').order('created_at')
    i = 0
    ((DateTime.now.utc.to_date - days_amount.days)..DateTime.now.utc.to_date).map do |d|
      if d.day == days_ops[i]&.created_at&.day
        i += 1
        {
          date: d.to_s,
          total: days_ops[i - 1].total.to_f.abs
        }
      else
        {
          date: d.to_s,
          total: 0
        }
      end
    end
  end

  def check_params
    params[:lchart_days] ||= '7'
    params[:page] ||= '0'
    params[:page_items] ||= '5'
  end

  def bar_chart_data
    current_user.categories.where.not(name: 'personal_budget').map do |c|
      {
        name: c.name,
        total: c.operations.sum(:amount).to_f.abs
      }
    end
  end
end

app/helpers/budget_helper.rb
# rubocop:disable Metrics/ModuleLength
module BudgetHelper
  def unavailable_balance?
    current_user.balance <= 0
  end

  def bar_chart_data
    {
      labels: @categories_expenses.map { |item| item[:name] },
      datasets: [
        {
          label: 'Expenses',
          data: @categories_expenses.map { |item| item[:total] },
          background_color: [
            'rgba(255, 99, 132, 0.3)',
            'rgba(255, 159, 64, 0.3)',
            'rgba(255, 205, 86, 0.3)',
            'rgba(75, 192, 192, 0.3)',
            'rgba(54, 162, 235, 0.3)',
            'rgba(153, 102, 255, 0.3)',
            'rgba(201, 203, 207, 0.3)'
          ],
          border_color: [
            'rgb(255, 99, 132)',
            'rgb(255, 159, 64)',
            'rgb(255, 205, 86)',
            'rgb(75, 192, 192)',
            'rgb(54, 162, 235)',
            'rgb(153, 102, 255)',
            'rgb(201, 203, 207)'
          ],
          border_width: 1
        }
      ]
    }
  end

  def bar_chart_options
    {
      index_axis: 'y',
      aspect_ratio: 1.5,
      plugins: {
        title: {
          text: 'Amount Expended x Category',
          display: true
        },
        tooltip: {
          callbacks: {
            label: 'function(context) {
              return `${context.dataset.label}: $${context.parsed.x}`
            }'
          }
        },
        legend: {
          display: false
        }
      },
      scales: {
        x: {
          ticks: {
            callback: 'function(value) {
              return `$${value}`;
            }'
          }
        }
      },
      datasets: {
        bar: {
          bar_percentage: 0.6
        }
      }
    }
  end

  def line_chart_data
    {
      labels: @last_days_ops.map { |item| item[:date] },
      datasets: [
        {
          label: 'Daily expenses',
          data: @last_days_ops.map { |item| item[:total] },
          background_color: [
            'rgba(54, 162, 235, 0.5)'
          ],
          border_color: [
            'rgb(54, 162, 235)'
          ],
          border_width: 1
        }
      ]
    }
  end

  def line_chart_options
    {
      aspect_ratio: 1.5,
      scales: {
        y: {
          ticks: {
            callback: 'function(value) {
              return `$${value}`;
            }'
          },
          begin_at_zero: true
        }
      },
      plugins: {
        title: {
          text: 'Expenses x Day',
          display: true
        },
        tooltip: {
          callbacks: {
            label: 'function(context) {
              return `${context.dataset.label}: $${context.parsed.y}`
            }'
          }
        }
      },
      interaction: {
        intersect: false,
        mode: 'index'
      }
    }
  end
end
# rubocop:enable Metrics/ModuleLength

app/views/budget/_form.html.erb
<%= form_with(model: operation, scope: 'operation', url: request.path, class: 'form',
              id: 'new_operation') do |form| %>
  <% if operation.errors.any? %>
    <div data-turbo-cache="false">
      <h2><%= pluralize(operation.errors.count, "error") %> prohibited this transaction from being processed:</h2>
      <ul>
        <% operation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'form_amount', form:, operation: %>

  <div class="field mb-2">
    <%= form.label :description, class: 'd-none' %>
    <%= form.text_area :description,
          class: 'form-control',
          placeholder: 'Description (optional)',
          disabled: unavailable_balance? && current_path?('/my_budget/withdraw') %>
    <div class="form-text">Add a an optional description to this transaction.</div>
  </div>

  <% if current_path? '/my_budget/deposit' %>
    <button class="btn btn-success px-3">Deposit <i class="fa-solid fa-arrow-up-from-bracket ms-1"></i></button>
  <% else %>
    <button class="btn btn-danger px-3" <%= 'disabled' if unavailable_balance? %>>Withdraw <i class="fa-solid fa-arrow-up-from-bracket ms-1" style="transform: rotate(180deg)"></i></button>
  <% end %>
<% end %>

app/views/budget/_form_amount.html.erb
<% if current_path? '/my_budget/deposit' %>
  <div class="field input-group">
    <span class="input-group-text">$</span>
    <%= form.label :amount, class: 'd-none' %>
    <input
      id="operation_amount"
      class="form-control"
      name="operation[amount]"
      placeholder="Amount"
      min="0"
      step="0.01"
      <% if operation.amount_before_type_cast && operation.amount_before_type_cast != '' %>
        value=<%= operation.amount_before_type_cast %>
      <% end %>
      autofocus
      type="number"
    >
  </div>
  <div class="form-text mb-2">Enter the amount of money you want to deposit.</div>
<% else %>
  <div class="field input-group">
    <span class="input-group-text">$</span>
    <%= form.label :amount, class: 'd-none' %>
    <input
      id="operation_amount"
      class="form-control"
      name="operation[amount]"
      placeholder="Amount"
      min="0"
      step="0.01"
      <% if operation.amount_before_type_cast && operation.amount_before_type_cast != '' %>
        value=<%= operation.amount_before_type_cast.abs %>
      <% end %>
      autofocus
      type="number"
      <%= 'disabled' if unavailable_balance? %>
    >
    <button
      class="btn btn-outline-secondary"
      type="button"
      onclick="document.getElementById('operation_amount').value = <%= current_user.balance %>"
      <%= 'disabled' if unavailable_balance? %>
    >
      Max
    </button>
  </div>
  <div class="form-text mb-2">Enter the amount of money you want to withdraw.</div>
<% end %>

app/views/budget/_header_index.html.erb
<%= link_to root_path, class: 'back-btn', data: { turbo_action: 'restore' } do %>
  <i class="fa-solid fa-arrow-left"></i>
<% end %>
<h2 class="mx-auto">MY BUDGET</h2>

app/views/budget/_header_transaction.html.erb
<%= link_to my_budget_path, class: 'back-btn', data: { turbo_action: 'restore' } do %>
  <i class="fa-solid fa-arrow-left"></i>
<% end %>
<h2 class="mx-auto">
  <% if current_path? '/my_budget/deposit' %>
    DEPOSIT MONEY
  <% else %>
    WITHDRAW MONEY
  <% end %>
</h2>

app/views/budget/index.html.erb
<% content_for :navbar do %>
  <%= render 'header_index' %>
<% end %>

<section class="d-flex flex-column h-100 pb-3 overflow-auto position-relative" id="modal-parent">
  <%= render 'components/balance_bar' %>
  <div class="container-fluid py-2">
    <div class="container-sm category-item flex-column">
      <h3 class="mb-2">Account metrics:</h3>
      <div class="container-fluid mb-2">
        <ul class="row row-cols-1 row-cols-sm-3 list-group list-group-horizontal list-unstyled">
          <li class="col gx-3 py-1">
            <div class="list-group-item list-group-item-success">
              <p class="mb-2 text-center">Total deposited</p>
              <p class="m-0 text-center">$<%= @total_deposits.to_f %></p>
            </div>
          </li>
          <li class="col gx-3 py-1">
            <div class="list-group-item list-group-item-warning">
              <p class="mb-2 text-center">Total expended</p>
              <p class="m-0 text-center">$<%= @total_expenses.to_f %></p>
            </div>
          </li>
          <li class="col gx-3 py-1">
            <div class="list-group-item list-group-item-danger">
              <p class="mb-2 text-center">Total withdrawn</p>
              <p class="m-0 text-center">$<%= @total_withdrawals.to_f.abs %></p>
            </div>
          </li>
        </ul>
      </div>
      <h4 class="text-decoration-underline">Expenses by categories</h4>
      <div class="position-relative mb-3" data-controller="previewing">
        <%= bar_chart bar_chart_data, bar_chart_options %>
        <% if @categories_expenses.empty? %>
          <div
            class="position-absolute text-center top-0 bottom-0 start-0 end-0 d-flex align-items-center justify-content-center"
            style="background: #7a848e38;"
          >
            There are no metrics available at this moment.
          </div>
        <% else %>
          <div
            data-previewing-target="loading"
            class="position-absolute d-flex d-none text-center top-0 bottom-0 start-0 end-0 align-items-center justify-content-center"
            style="background: #7a848e38;"
          >
            <div class="spinner-border text-primary" role="status">
              <span class="visually-hidden">Loading...</span>
            </div>
          </div>
        <% end %>
      </div>
      <h4 class="text-decoration-underline m-0">Daily transactions</h4>
      <turbo-frame id="line-chart">
        <div class="position-relative" data-controller="previewing">
          <div class="text-end">
            <%= 
              link_to_if params[:lchart_days] == '7', 'Last 14 days', url_for(only_path: true, params: { lchart_days: 14 }) do
                link_to 'Last 7 days', url_for(only_path: true, params: { lchart_days: 7 })
              end 
            %>
          </div>
          <%= line_chart line_chart_data, line_chart_options %>
          <div
            data-previewing-target="loading"
            class="position-absolute d-flex d-none text-center top-0 bottom-0 start-0 end-0 align-items-center justify-content-center"
            style="background: #7a848e38;"
          >
            <div class="spinner-border text-primary" role="status">
              <span class="visually-hidden">Loading...</span>
            </div>
          </div>
        </div>
      </turbo-frame>
    </div>
  </div>
  <div class="container-fluid bg-light py-2">
    <div class="container-sm">
      <h3 class="m-0 fs-4">Transactions history</h3>
    </div>
  </div>
  <% if @user_budget_ops.empty? %>
    <p class="text-center mt-3">There are no transactions yet.</p>
  <% else %>
    <div class="container-fluid">
      <div class="container-sm pt-2">
        <ul class="categories-list gap-1">
          <turbo-frame id="page-<%= params[:page] %>">
            <%= render partial: 'categories/operation', collection: @user_budget_ops %>
            <div class="text-center">
              <% if params[:page].to_i + 1 < max_pages(@budget_operations_length) %>
                <%= link_to 'Load older transactions', url_for(only_path: true, params: { page: params[:page].to_i + 1, page_items: params[:page_items] }),
                            data: { turbo_frame: "page-#{params[:page].to_i + 1}" }, onclick: 'this.style.display = "none"' %>
              <% end %>
            </div>
            <turbo-frame id="page-<%= params[:page].to_i + 1 %>">
            </turbo-frame>
          </turbo-frame>
        </ul>
      </div>
    </div>
  <% end %>
  
  <turbo-frame id="operation-modal">
  </turbo-frame>

</section>

app/views/budget/new_transaction.html.erb
<% content_for :navbar do %>
  <%= render 'header_transaction' %>
<% end %>

<section class="overflow-auto">
  <%= render 'components/balance_bar' %>
  <% if unavailable_balance? && current_path?('/my_budget/withdraw') %>
    <div data-turbo-cache="false" class="alert alert-danger py-2 fade show m-0" role="alert">
      <strong>
        You don't have available balance to proceed with this operation.
        <%= link_to 'Click here to deposit money', my_budget_deposit_path %>
      </strong>
    </div>
  <% end %>
  <div class="container-sm py-3 position-relative" data-controller="previewing">
    <%= render 'form', operation: @operation %>
    <div
      data-previewing-target="loading"
      class="position-absolute d-flex d-none text-center top-0 bottom-0 start-0 end-0 align-items-center justify-content-center"
      style="background: #7a848e38;"
    >
      <div class="spinner-border text-primary" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>
  </div>
</section>