config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { edit: 'account' }, controllers: { registrations: 'registrations',
                                                                               sessions: 'sessions' }

  resources :categories do
    resources :operations, except: %i[index show]
  end

  resources :operations, only: %i[index show update]

  get 'categories/:id/operations', to: redirect('categories/%{id}')

  get 'my_budget', to: 'budget#index'
  get 'my_budget/deposit', to: 'budget#new_deposit'
  post 'my_budget/deposit', to: 'budget#exec_deposit'
  get 'my_budget/withdraw', to: 'budget#new_withdraw'
  post 'my_budget/withdraw', to: 'budget#exec_withdraw'

  # devise_scope :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   get 'sign_up', to: 'devise/registrations#new'
  #   get 'account', to: 'devise/registrations#edit'
  #   get 'password/new', to: 'devise/passwords#new'
  #   get 'password/edit', to: 'devise/passwords#edit'
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "categories#index"

  get 'get-image', to: 'utils#fetch_image'
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :operations, dependent: :destroy
  has_one_attached :icon
  belongs_to :user

  validates_associated :user, :operations
  validates :name, presence: true, length: { maximum: 20 }
  validates :name, uniqueness: { case_sensitive: false }, on: :category_creation
  validates :description, length: { maximum: 300 }, on: :category_creation
  validates :icon, presence: true, on: :category_creation

  validates :icon, file_size: { less_than_or_equal_to: 1.megabytes },
                   file_content_type: { allow: ['image/jpeg', 'image/png', 'image/gif'] }
end

app/controllers/categories_controller.rb
require 'utils/fetch_url'

class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: %i[index]
  before_action :set_category, only: %i[show edit update destroy]
  before_action :check_params, only: [:show]

  def index
    if user_signed_in?
      @categories = if params[:search].present?
                      current_user.categories.includes([icon_attachment: :blob])
                        .where('name ~* ? and name != ?', params[:search], 'personal_budget').order name: :asc
                    else
                      current_user.categories.includes([icon_attachment: :blob]).where('name != ?', 'personal_budget')
                        .order name: :asc
                    end

      render(:index) and return if params[:ref].nil?

      render layout: 'after_update'
    else
      render :home
    end
  end

  def show
    @operations_length = @category.operations.length
    @category_operations = @category.operations.order(created_at: :desc).limit(params[:page_items].to_i)
      .offset(params[:page].to_i * params[:page_items].to_i)
    render layout: 'no_preview'
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(**category_params, user: current_user)

    unless params[:img].nil?
      req = FetchUrl.new(params[:img])

      if req.ok?
        @category.icon.attach(io: StringIO.new(req.response.read_body),
                              filename: "#{@category.name}_category.#{req.response.content_type.split('/')[1]}",
                              content_type: req.response.content_type)
      else
        @category.errors.add(:icon, :invalid, message: 'is invalid.')
        render :new, status: :unprocessable_entity
        return
      end
    end

    if @category.save(context: :category_creation)
      redirect_to categories_path, notice: 'Category created successfully.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    category_params = self.category_params
    unless params[:img].nil?
      req = FetchUrl.new(params[:img])

      if req.ok?
        category_params[:icon] = build_tempfile req.response.read_body,
                                                req.response.content_type.split('/')[1],
                                                req.response.content_type
      else
        @category.errors.add(:icon, :invalid, message: 'is invalid.')
        render :edit, status: :unprocessable_entity and return
      end
    end

    if @category.update(category_params)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to category_path(params[:id]), notice: 'Category updated successfully.' }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy

    redirect_to root_path, notice: 'Category deleted successfully.', status: :see_other
  end

  private

  def category_params
    params.require(:category).permit :name, :icon, :description
  end

  def set_category
    @category = current_user.categories.find(params[:id])
  end

  def check_params
    params[:page] ||= '0'
    params[:page_items] ||= '5'
  end

  def build_tempfile(body, filename, type)
    tmp = Tempfile.new
    tmp.binmode
    tmp << body
    ActionDispatch::Http::UploadedFile
      .new({
             tempfile: tmp,
             filename:,
             type:
           })
  end
end

app/views/categories/_category.html.erb
<li class="category-item">
  <%= link_to category_path(category), class: 'd-flex w-100 text-decoration-none' do %>
    <%= image_tag category.icon, alt: 'icon', class: 'category-item-icon flex-shrink-0' %>
    <div class="px-2 d-flex flex-column overflow-hidden">
      <p class="mt-2 mb-0 text-truncate"><%= category.name %></p>
      <small class="mt-auto"><%= category.created_at.strftime "%m-%d-%Y" %></small>
    </div>
    <div class="ms-auto">
      <p>$<%= category.operations.sum(:amount).abs %></p>
    </div>
  <% end %>
</li>

app/views/categories/_category_details.html.erb
<div class="category-item flex-column">
  <div class="d-flex align-items-center">
    <%= image_tag @category.icon, alt: 'icon', class: 'category-item-icon', data: { avatar_target: 'preview' } %>
    <h3 class="m-0 ms-3 overflow-hidden"><%= @category.name %></h3>
    <div class="dropdown align-self-start ms-auto">
      <button class="btn btn-link fs-5 py-1" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="fa-solid fa-ellipsis-vertical"></i>
      </button>
      <ul class="dropdown-menu">
        <li>
          <%= link_to edit_category_path(params[:id]), class: 'dropdown-item' do %>
            <i class="fa-solid fa-pencil text-primary"></i>
            <span>Edit</span>
          <% end %>
        </li>
        <li>
          <button class="dropdown-item" data-action="categories#delete" data-categories-id-param="<%= @category.id %>">
            <i class="fa-solid fa-trash text-primary"></i>
            <span>Delete</span>
          </button>
        </li>
      </ul>
    </div>
  </div>
  <div class="p-2">
    <% if  @category.description.nil? || @category.description.empty? %>
      <p class="fst-italic text-gray-600 m-0">No provided description.</p>
    <% else %>
      <p class="m-0"><%= @category.description %></p>
    <% end %>
  </div>
  <div class="px-2 d-flex flex-column mt-2">
    <small class="mt-auto">Created at: <%= @category.created_at.strftime "%m-%d-%Y" %></small>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, url: categories_path, class: 'form', id: 'new_category') do |form| %>
  <% if category.errors.any? %>
    <div data-turbo-cache="false">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field avatar mb-3" data-controller="avatar" data-avatar-placeholder-pic-value=<%= asset_path 'placeholder-icon.png' %>>
    <div class="preview">
      <%= image_tag 'placeholder-icon.png', data: { avatar_target: 'preview' }, alt: 'category-icon',
                                            class: 'rounded' %>
    </div>
    <div class="image-upload overflow-hidden" data-avatar-target="uploadArea">
      <div class="d-flex align-items-center mb-2 flex-wrap" style="column-gap: 0.5rem; row-gap: 0.3rem;">
        <div class="file-picker">
          <%= form.label :icon, 'Upload icon', class: 'btn btn-link p-0' %>
          <%= form.file_field :icon, data: { action: 'change->avatar#update', avatar_target: 'picture' },
                                    accept: 'image/jpeg, image/png, image/gif' %>
        </div>
        <div>|</div>
        <div>
          <button type="button" class="btn btn-link p-0" style="font-size: 1.2rem" data-action="avatar#showUrlInput">
            Load from URL
          </button>
        </div>
      </div>
      <div class="file-selection">
        <small data-avatar-target="fileName">No file chosen...</small>
        <button type="button" class="d-none" data-avatar-target="clearBtn" data-action="click->avatar#destroy">
          <i class="fa-solid fa-xmark"></i>
        </button>
      </div>
    </div>
  </div>

  <div class="field mb-2">
    <%= form.label :name, class: 'd-none' %>
    <%= form.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control', placeholder: 'Name' %>
  </div>

  <div class="field">
    <%= form.label :description, class: 'd-none' %>
    <%= form.text_area :description, class: 'form-control', placeholder: 'Description (optional)', rows: '4' %>
  </div>

<% end %>

app/views/categories/_header_index.html.erb
<button
  class="navbar-toggler p-0"
  type="button"
  
  aria-controls="offcanvasNavbar"
  data-controller="open-menu"
  data-action="open-menu#openMenu"
>
  <span class="navbar-toggler-icon"></span>
</button>
<h2 class="mx-lg-auto">CATEGORIES</h2>
<button type="button" class="action-btn btn btn-link text-light fs-5 p-0 off" data-controller="search-item" data-action="search-item#update"
        data-search-item-state-value="false" id="search-categories">
  <i class="fa-solid fa-magnifying-glass item-on"></i>
  <i class="fa-solid fa-xmark item-off"></i>
</button>

app/views/categories/_header_new.html.erb
<%= link_to root_path, class: 'back-btn', data: { turbo_action: 'restore' } do %>
  <i class="fa-solid fa-arrow-left"></i>
<% end %>
<h2>NEW CATEGORY</h2>
<button form="new_category" class="action-btn btn btn-link text-light fs-5 p-0">Save</button>

app/views/categories/_header_show.html.erb
<%= link_to root_path, class: 'back-btn' do %>
  <i class="fa-solid fa-arrow-left"></i>
<% end %>
<h2 class="mx-auto">TRANSACTIONS</h2>

app/views/categories/_operation.html.erb
<li class="category-item mb-1 operation-item">
  <%= link_to (request.path.match(/\/categories\/\d+/) ? operation_path(operation, category: params[:id]) : operation_path(operation, ref: request.parameters[:controller])),
              class: "d-flex w-100 text-decoration-none #{operation.amount.negative? ? 'text-danger' : 'text-success'}",
              data: { turbo_frame: 'operation-modal', controller: 'modal', action: 'modal#show', modal_modal_id_value: "operation-#{operation.id}" } do
  %>
    <div class="px-2 d-flex flex-column overflow-hidden">
      <p class="m-0 text-truncate"><%= operation.name %></p>
      <small class="mt-auto text-gray-600"><%= operation.created_at.localtime.strftime "%b %d %Y at %l:%M %P" %> | Nº <%= operation.id %></small>
    </div>
    <div class="ms-auto">
      <% if operation.amount.negative? %>
        <p>-$<%= operation.amount.abs %></p>
      <% else %>
        <p>+$<%= operation.amount %></p>
      <% end %>
    </div>
  <% end %>
</li>

app/views/categories/edit.html.erb
<turbo-frame id="edit-category">
  <%= form_with(model: @category, url: category_path, class: 'form', id: 'edit_category',
                data: { avatar_target: 'form' }, html: { enctype: 'multipart/form-data' }) do |form| %>
    <div class="category-item flex-column">
      <% if @category.errors.any? %>
        <div data-turbo-cache="false">
          <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
          <ul>
            <% @category.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="d-flex align-items-center">
        <div class="category-item-icon position-relative">
          <%= image_tag @category.icon, alt: 'icon', class: 'w-100 h-100', style: 'object-fit: cover',
                                        data: { avatar_target: 'preview' } %>
          <button
            type="button"
            class="position-absolute top-0 start-0 btn btn-link pt-0 ps-1 blurred-radial-gradient link-light"
            data-action="categories#showIconUpdater"
          >
            <i class="fa-solid fa-pencil"></i>
          </button>
        </div>
        <div class="field ms-3 me-2 w-100">
          <%= form.label :name, class: 'd-none' %>
          <%= form.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control fs-3', placeholder: 'Name' %>
        </div>
      </div>
      <div class="field p-2">
        <%= form.label :description, class: 'd-none' %>
        <%= form.text_area :description, class: 'form-control', placeholder: 'Description (optional)', rows: '2' %>
      </div>
      <div class="px-2 d-flex gap-2">
        <button class="btn btn-primary" type="submit">Save</button>
        <%= link_to 'Cancel', category_path(params[:id]), class: 'btn btn-secondary' %>
      </div>
    </div>
  <% end %>
</turbo-frame>

app/views/categories/home.html.erb
<section class="container-fluid h-100 home">
  <div class="container-sm h-100 d-flex flex-column justify-content-between py-3">
    <h1 class="my-auto text-center">MyBudgetApp</h1>
    <div class="d-flex flex-wrap justify-content-center action-btns">
      <%= link_to 'LOG IN', new_user_session_path, class: 'btn btn-primary' %>
      <%= link_to 'SIGN UP', new_user_registration_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</section>

app/views/categories/index.html.erb
<% content_for :navbar do %>
  <%= render 'header_index' %>
<% end %>

<section class="pb-3 d-flex flex-column h-100 overflow-hidden">
  <% if params[:search].present? %>
    <div class="container-fluid py-2 bg-light" data-turbo-cache="false">
      <div class="container-sm d-flex">
        <p class="m-0">Searching <span class="fw-bold">"<%= params[:search] %>"</span></p>
        <%= link_to categories_path, class: 'btn btn-link py-0', title: 'Clear search' do %>
          <i class="fa-solid fa-xmark"></i>
        <% end %>
      </div>
    </div>
  <% end %>
  <div hidden class="container-fluid bg-light py-2" style="margin-top: -1px" data-controller="search-item" data-action="search-item:update@window->search-item#toggleComponent">
    <form class="input-group container-sm px-0" method="get" action="/categories">
      <input type="text" class="form-control" required name="search" placeholder="Search by category name" aria-label="Search by category name" aria-describedby="search-btn">
      <button class="btn btn-secondary" type="submit" id="search-btn">Search</button>
    </form>
  </div>
  <%= render 'components/balance_bar' %>
  <div class="container-fluid pt-2 d-flex flex-column categories overflow-auto">
    <div class="container-sm d-flex flex-column">
      <% if @categories.empty? %>
        <% if params[:search].present? %>
          <h3 class="text-center">There are nor results for the search query.</h3>
        <% else %>
          <h3 class="text-center">There are no categories yet.</h3>
        <% end %>
      <% else %>
        <ul class="categories-list">
          <%= render @categories %>
        </ul>
      <% end %>
    </div>
  </div>
  <div class="mt-auto new-category-btn container-fluid">
    <%= link_to 'ADD NEW CATEGORY', new_category_path, class: 'btn btn-secondary' %>
  </div>
</section>

app/views/categories/new.html.erb
<% content_for :navbar do %>
  <%= render 'header_new' %>
<% end %>

<section class="container-fluid">
  <div class="container-sm py-3 px-0 position-relative" data-controller="previewing">
    <%= render 'form', category: @category %>
    <div
      data-previewing-target="loading"
      class="position-absolute d-flex d-none text-center top-0 bottom-0 start-0 end-0 align-items-center justify-content-center"
      style="background: #7a848e38;"
    >
      <div class="spinner-border text-primary" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>
  </div>
</section>

app/views/categories/show.html.erb
<% content_for :navbar do %>
  <%= render 'header_show' %>
<% end %>

<section
  class="d-flex flex-column h-100 pb-3 overflow-hidden"
  id="modal-parent"
  data-controller="categories avatar"
  data-action="avatar:closemodal->categories#hideIconUpdater"
>
  <div class="overflow-auto">
    <div class="container-fluid bg-light sticky-top">
      <div class="container-sm py-2">
        <p class="m-0">Total expenses: <span class="fw-bold">$<%= @category.operations.sum(:amount).abs %></span></p>
      </div>
    </div>
    <div class="container-fluid">
      <div class="container-sm py-2 px-0">
        <turbo-frame id="edit-category">
          <%= render 'category_details' %>
        </turbo-frame>
      </div>
    </div>
    <div class="container-fluid bg-light py-2">
      <div class="container-sm">
        <h4 class="m-0">Latest transactions</h4>
      </div>
    </div>
    <% if @category_operations.empty? %>
      <p class="text-center mt-3">There are no transactions yet.</p>
    <% else %>
      <div class="container-fluid overflow-auto">
        <div class="container-sm pt-2">
          <ul class="categories-list">
            <turbo-frame id="page-<%= params[:page] %>">
              <%= render partial: 'operation', collection: @category_operations %>
              <div class="text-center">
                <% if params[:page].to_i + 1 < max_pages(@operations_length) %>
                  <%= link_to 'Load older transactions', url_for(only_path: true, params: { page: params[:page].to_i + 1, page_items: params[:page_items] }),
                              data: { turbo_frame: "page-#{params[:page].to_i + 1}" }, onclick: 'this.style.display = "none"' %>
                <% end %>
              </div>
              <turbo-frame id="page-<%= params[:page].to_i + 1 %>">
              </turbo-frame>
            </turbo-frame>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
  <div class="mt-auto new-category-btn container-fluid">
    <%= link_to 'NEW TRANSACTION', new_category_operation_path(@category), class: 'btn btn-secondary' %>
  </div>

  <turbo-frame id="operation-modal">
  </turbo-frame>

</section>

app/views/categories/update.turbo_stream.erb
<%= turbo_stream.update 'flash-messages' do %>
  <div data-turbo-cache="false" class="alert alert-secondary alert-dismissible fade show m-0"role="alert">
    <strong>Category updated successfully.</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<%= turbo_stream.update 'edit-category' do %>
  <%= render 'category_details' %>
<% end %>