config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { edit: 'account' }, controllers: { registrations: 'registrations',
                                                                               sessions: 'sessions' }

  resources :categories do
    resources :operations, except: %i[index show]
  end

  resources :operations, only: %i[index show update]

  get 'categories/:id/operations', to: redirect('categories/%{id}')

  get 'my_budget', to: 'budget#index'
  get 'my_budget/deposit', to: 'budget#new_deposit'
  post 'my_budget/deposit', to: 'budget#exec_deposit'
  get 'my_budget/withdraw', to: 'budget#new_withdraw'
  post 'my_budget/withdraw', to: 'budget#exec_withdraw'

  # devise_scope :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   get 'sign_up', to: 'devise/registrations#new'
  #   get 'account', to: 'devise/registrations#edit'
  #   get 'password/new', to: 'devise/passwords#new'
  #   get 'password/edit', to: 'devise/passwords#edit'
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "categories#index"

  get 'get-image', to: 'utils#fetch_image'
end

app/views/navigation/_sidebar.html.erb
<nav class="navbar navbar-dark bg-primary navbar-expand-lg sidebar">
  <div
    class="offcanvas-lg offcanvas-start"
    data-controller="slide-menu"
    data-action="open-menu:openmenu@document->slide-menu#open"
    tabindex="-1"
    id="offcanvasNavbar"
    <% if persist %>
      data-turbo-permanent
    <% end %>
    aria-labelledby="offcanvasNavbarLabel"
  >
    <div class="offcanvas-header">
      <h1 class="offcanvas-title text-light" id="offcanvasNavbarLabel">
        <%= link_to 'MyBudgetApp', root_path, class: 'text-reset text-decoration-none' %>
      </h1>
      <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" data-bs-target="#offcanvasNavbar" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body pt-0">
      <div class="avatar mb-2" data-controller="flex-wrapped-helper" data-flex-wrapped-helper-minwidth-value="992" data-flex-wrapped-helper-triggered-class="flex-wrapped">
        <figure class="figure rounded-circle border overflow-hidden">
          <% if current_user.avatar.present? %>
            <%= image_tag current_user.avatar, alt: 'avatar' %>
          <% else  %>
            <%= image_tag 'profile-pic.png', alt: 'avatar' %>
          <% end %>
        </figure>
        <p data-flex-wrapped-helper-target="element"><%= current_user.name %></p>
      </div>
      <ul class="navbar-nav justify-content-end flex-grow-1 fs-5">
        <li class="nav-item" data-controller="navbar-link" data-navbar-link-name-value="Categories" data-navbar-link-paths-value="<%= [root_path, categories_path] %>">
          <%= link_to 'Categories', root_path, class: 'nav-link', aria: { current: 'page' } %>
        </li>
        <li class="nav-item" data-controller="navbar-link" data-navbar-link-name-value="My budget" data-navbar-link-paths-value="<%= [my_budget_path] %>">
          <%= link_to 'My budget', my_budget_path, class: 'nav-link', aria: { current: 'page' } %>
        </li>
        <li class="nav-item" data-controller="navbar-link" data-navbar-link-name-value="Account settings" data-navbar-link-paths-value="<%= [edit_user_registration_path] %>">
          <%= link_to 'Account settings', edit_user_registration_path, class: 'nav-link', aria: { current: 'page' } %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, class: 'nav-link', aria: { current: 'page' },
                                                            data: { turbo_method: 'delete' }, status: :see_other %>
        </li>
      </ul>
    </div>
  </div>
</nav>