config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { edit: 'account' }, controllers: { registrations: 'registrations',
                                                                               sessions: 'sessions' }

  resources :categories do
    resources :operations, except: %i[index show]
  end

  resources :operations, only: %i[index show update]

  get 'categories/:id/operations', to: redirect('categories/%{id}')

  get 'my_budget', to: 'budget#index'
  get 'my_budget/deposit', to: 'budget#new_deposit'
  post 'my_budget/deposit', to: 'budget#exec_deposit'
  get 'my_budget/withdraw', to: 'budget#new_withdraw'
  post 'my_budget/withdraw', to: 'budget#exec_withdraw'

  # devise_scope :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   get 'sign_up', to: 'devise/registrations#new'
  #   get 'account', to: 'devise/registrations#edit'
  #   get 'password/new', to: 'devise/passwords#new'
  #   get 'password/edit', to: 'devise/passwords#edit'
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "categories#index"

  get 'get-image', to: 'utils#fetch_image'
end

app/models/operation.rb
class Operation < ApplicationRecord
  has_and_belongs_to_many :categories
  belongs_to :user

  validates_associated :user
  validates :categories, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 300 }
  validates :amount, numericality: true, presence: true,
                     format: { with: /\A[-+]?\d+(?:\.\d{0,2})?\z/, message: 'max two decimal positions' }
  validates :amount, comparison: { other_than: 0, message: 'must be greater than 0' }

  def invalidate_user_balance
    errors.add :base, :invalid, message: 'Insufficient balance'
  end

  def invalidate_negative_amount
    errors.add :amount, :invalid, message: 'must be greater than 0'
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :authenticate_user!

  def show
    @operation = current_user.operations.includes(categories: { icon_attachment: :blob }).find params[:id]
  end

  def new
    @operation = Operation.new
    @current_category = current_user.categories.find(params[:category_id])
    others_categories params[:category_id]
  end

  def create
    parsed_params = operation_params
    parsed_params[:categories] = parse_categories_param parsed_params[:categories], params[:category_id]
    operation_amount = parsed_params[:amount].to_f
    @operation = Operation.new(**parsed_params, amount: -operation_amount, user: current_user)

    @operation.transaction do
      @operation.save!
      if (operation_amount > current_user.balance) || amount_negative?(operation_amount)
        raise ActiveRecord::RecordInvalid
      end

      current_user.update! balance: current_user.balance - operation_amount
    end

    redirect_to category_path(params[:category_id]), notice: 'Transaction created successfully.'
  rescue ActiveRecord::RecordInvalid
    current_user.balance = current_user.balance_was
    @operation.invalidate_negative_amount if amount_negative?(operation_amount)
    @operation.invalidate_user_balance if operation_amount > current_user.balance
    @current_category = current_user.categories.find(params[:category_id])
    others_categories params[:category_id]
    render :new, status: :unprocessable_entity
  end

  def update
    operation_to_revert = Operation.find params[:id]

    if operation_to_revert.created_at < Time.now - 2.days
      error = 'Only operations less than 2 days old can be reversed.'
      raise ActiveRecord::RecordInvalid
    end

    reverted_operation = Operation.new user: current_user, name: "[Refunded]#{operation_to_revert.name}",
                                       amount: -operation_to_revert.amount, reverted: true,
                                       description: 'Transaction reverted by the user.',
                                       categories: operation_to_revert.categories

    Operation.transaction do
      operation_to_revert.update! reverted: true
      reverted_operation.save!
      current_user.update! balance: current_user.balance + -operation_to_revert.amount
    end

    redirect_to category_path(operation_params[:category_id]),
                notice: "Operation ##{operation_to_revert.id} successfully refunded."
  rescue ActiveRecord::RecordInvalid => e
    error ||= e.record.errors.to_json
    redirect_to category_path(operation_params[:category_id]), notice: "Something went wrong: #{error}"
  end

  private

  def operation_params
    params.require(:operation).permit :name, :amount, :categories, :description, :category_id, :reverted
  end

  def others_categories(current_cat)
    @others_categories = current_user.categories.includes([icon_attachment: :blob]).where.not(id: current_cat)
      .where.not(name: 'personal_budget')
  end

  def parse_categories_param(categories_param, current_cat)
    if categories_param.nil? || categories_param.empty?
      [Category.find(current_cat)]
    else
      Category.find(JSON.parse(categories_param) << current_cat)
    end
  end
end

app/views/operations/_category.html.erb
<li data-id=<%= category.id %>>
  <button type="button" class="dropdown-item d-flex align-items-center gap-2" data-dropdown-picker-id-param=<%= category.id %>
          data-action="dropdown-picker#pick">
    <img src=<%= url_for category.icon %> class="icon-thumbnail dropdow-icon-thumbnail" alt="category item">
    <p class="m-0 text-truncate"><%= category.name %></p>
  </button>
</li>

app/views/operations/_form.html.erb
<%= form_with(model: operation, url: category_operations_path, class: 'form', id: 'new_operation') do |form| %>
  <% if operation.errors.any? %>
    <div data-turbo-cache="false">
      <h2><%= pluralize(operation.errors.count, "error") %> prohibited this transaction from being processed:</h2>
      <ul>
        <% operation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-2">
    <%= form.label :name, class: 'd-none' %>
    <%= form.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control', placeholder: 'Operation name eg. Buy pizza' %>
  </div>

  <div class="field input-group mb-2">
    <span class="input-group-text">$</span>
    <%= form.label :amount, class: 'd-none' %>
    <input
      id="operation_amount"
      type="number"
      class="form-control"
      name="operation[amount]"
      placeholder="Amount"
      min="0"
      step="0.01"
      value=<%= operation.amount_before_type_cast&.abs %>
    >
  </div>

  <div class="field">
    <%= form.label :description, class: 'd-none' %>
    <%= form.text_area :description, class: 'form-control', placeholder: 'Description (optional)', rows: '4' %>
  </div>

  <div class="mt-2 p-2 bg-light border border-gray-400 rounded">
    <p class="mb-1 text-gray-600">Current category:</p>
    <div class="d-flex gap-2">
      <img src=<%= url_for current_category.icon %> class="icon-thumbnail" alt="current category">
      <p class="my-auto fs-4"><%= current_category.name %></p>
    </div>
  </div>

  <% if others_categories.any? %>
    <div class="mt-2 p-2 bg-light border border-gray-400 rounded" data-controller="dropdown-picker"
         data-action="dropdown-picker:updated@window->dropdown-picker#updateDropdownList selected-item:unselect@window->dropdown-picker#unselect">
      <ul class="m-0 list-group">
        <%= render partial: 'selected_category', collection: others_categories %>
      </ul>
      <div class="dropdown" data-dropdown-picker-target="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
          Add another category
        </button>
        <ul class="dropdown-menu dropdown-menu-dark mw-100" aria-labelledby="dropdownMenuButton" data-dropdown-picker-target="dropdownList">
          <%= render partial: 'category', collection: others_categories %>
        </ul>
      </div>
      <input type="hidden" name="operation[categories]" data-dropdown-picker-target="categoriesInput">
    </div>
  <% end %>

<% end %>

app/views/operations/_header_new.html.erb
<%= link_to category_path(params[:category_id]), class: 'back-btn', data: { turbo_action: 'restore' } do %>
  <i class="fa-solid fa-arrow-left"></i>
<% end %>
<h2 class="mx-auto text-truncate px-1">NEW TRANSACTION</h2>
<button form="new_operation" class="action-btn btn btn-link text-light fs-5 p-0">Save</button>

app/views/operations/_selected_category.html.erb
<li style="display: flex" class="list-group-item align-items-center gap-2" hidden data-controller="selected-item" data-action="dropdown-picker:select@window->selected-item#select"
    data-selected-item-id-value=<%= selected_category.id %>>
  <img src=<%= url_for selected_category.icon %> class="icon-thumbnail dropdow-icon-thumbnail" alt="selected category">
  <p class="m-0 text-truncate"><%= selected_category.name %></p>
  <button type="button" data-action="selected-item#remove" class="ms-auto btn btn-link">
    <i class="fa-solid fa-xmark"></i>
  </button>
</li>

app/views/operations/new.html.erb
<% content_for :navbar do %>
  <%= render 'header_new' %>
<% end %>

<section class="container-fluid px-0 overflow-auto">
  <%= render 'components/balance_bar' %>
  <div class="container-sm py-3 position-relative" data-controller="previewing">
    <%= render 'form', operation: @operation, current_category: @current_category, others_categories: @others_categories %>
    <div
      data-previewing-target="loading"
      class="position-absolute d-flex d-none text-center top-0 bottom-0 start-0 end-0 align-items-center justify-content-center"
      style="background: #7a848e38;"
    >
      <div class="spinner-border text-primary" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
  </div>
</section>

app/views/operations/show.html.erb
<turbo-frame id="operation-modal">
  <div class="modal fade" id="operation-<%= params[:id] %>" tabindex="-1" aria-labelledby="operationModalLabel" aria-hidden="true" data-turbo-cache="false">
    <div class="modal-dialog modal-dialog-scrollable">
      <div class="modal-content" data-controller="operation-modal">
        <div class="modal-header">
          <h5 class="modal-title" id="operationModalLabel">Operation #<%= @operation.id %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body position-relative" data-operation-modal-target="modalBody">
          <p><span class="fw-bold">Date:</span> <%= @operation.created_at.localtime.strftime "%b %d %Y at %l:%M %P" %> </p>
          <p><span class="fw-bold">Name:</span> <%= @operation.name %> </p>
          <p>
            <span class="fw-bold">Amount:</span>
            <% if @operation.amount.negative? %>
              <span class="text-danger">-$<%= @operation.amount.abs %></span>
            <% else %>
              <span class="text-success">+$<%= @operation.amount %></span>
            <% end %>
          </p>
          <p>
            <span class="fw-bold">Description:</span>
            <% if @operation.description.empty? %>
              <span class="fst-italic text-gray-600">No description was provided for this operation.</span>
            <% else %>
              <%= @operation.description %>
            <% end %>
          </p>
          <div>
            <p><span class="fw-bold">Categories:</span></p>
            <ul class="m-0">
              <% if @operation.categories.first.name == 'personal_budget' %>
                <li class="dropdown-item d-flex align-items-center gap-2">
                  <p class="m-0 fst-italic text-gray-600">Personal balance</p>
                </li>
              <% else %>
                <% @operation.categories.each do |category| %>
                  <li class="dropdown-item d-flex align-items-center gap-2 mb-2">
                    <img src=<%= url_for category.icon %> class="icon-thumbnail dropdow-icon-thumbnail" alt="category item">
                    <p class="m-0 text-truncate"><%= category.name %></p>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="modal-footer">
          <% unless params[:ref] == 'budget' || @operation.reverted %>
            <div class="dropdown">
              <button
                class="btn btn-primary dropdown-toggle"
                type="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
                data-operation-modal-target="dropdownBtn"
              >
                Actions
              </button>
              <ul class="dropdown-menu dropdown-menu-dark">
                <li>
                  <button
                    class="dropdown-item"
                    type="button"                    
                    <% if @operation.created_at < Time.now - 2.days %>
                      data-action="operation-modal#showError"
                      data-operation-modal-error-param="This operation cannot be reverted. Only operations less than 2 days old can be refunded."
                    <% else %>
                      data-action="operation-modal#confirm"
                      data-operation-modal-action-param="revert"
                      data-operation-modal-action-params-param='{"id":"<%= @operation.id %>","category-id":"<%= params[:category] %>"}'
                    <% end %>
                  >
                    Revert operation
                  </button>
                </li>
              </ul>
            </div>
          <% end %>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</turbo-frame>